gb/gb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from mainapp import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', views.contact, name='contact'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

gb/mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.products, name='products'),
    path('<int:pk>/', views.products_list, name='category')
]

gb/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='user_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

gb/mainapp/models.py
from xml.etree.ElementInclude import default_loader
from django.db import models


class Category(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return f'Name: {self.name}, id: {self.pk} '


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя', max_length=64)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_des = models.CharField(
        verbose_name='краткое описание продукта', max_length=128, blank=True)
    description = models.TextField(
        verbose_name='описание продукта', blank=True)
    price = models.DecimalField(
        verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе', default=0)

    def __str__(self):
        return f'Name: {self.name}, category: {self.category.name}, price: {self.price}'

gb/authapp/views.py
from django.shortcuts import render

# Create your views here.

gb/mainapp/views.py
from django.shortcuts import render
from .models import Category, Product


def index(request):
    return render(request, 'mainapp/index.html', context={'products': Product.objects.all()[:2]})


def products(request):
    return render(request, 'mainapp/products.html', context={'category': Category.objects.all()})


def products_list(request, pk):
    return render(request, 'mainapp/products.html', context={'category': Category.objects.all()})


def contact(request):
    return render(request, 'mainapp/contact.html')

gb/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	{% block title %}
		<title>Магазин</title>
	{% endblock title %}
	{% block css %}
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
	{% endblock css %}
</head>
<body>
    {% block content %}
    {% endblock content %}

    {% block footer %}
	    <div class="footer">
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>
                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>
                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>
            <p class="small">&copy; GB 2017</p>
            <div class="social">
                <a href="#" class="social1"></a>
                <a href="#" class="social2"></a>
                <a href="#" class="social3"></a>
                <a href="#" class="social4"></a>
            </div>
            <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
        </div>	
    {% endblock footer %}
</body>
</html>

gb/mainapp/templates/mainapp/contact.html
{% extends "mainapp/base.html" %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<body>
	<div class="container">
		<div class="hero">
			{% include "mainapp/includes/inc_menu.html" %}
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>	
</body>
{% endblock %}

gb/mainapp/templates/mainapp/includes/inc_block_product.html
{% load static %}
{% for product in products %}
    <div class="block">
        <a href="#"><img src="/media/{{ product.image }}" alt="{{ product.description}}">
            <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="">
                <h4>{{ product.name }}</h4>
                <p>{{ product.short_des }}</p>
            </div>
        </a>
    </div>
{% endfor %}	

gb/mainapp/templates/mainapp/includes/inc_category_menu.html
<div class="details">
	<div class="links clearfix">
		<ul class="links-menu">
        {% for link in category %}
            <li><a href= "{% url 'products:category' link.pk %}" {% if  request.resolver_match.url_name == link.pk %}
            class="active"{% endif %}>{{ link.name }}</a></li>
        {% endfor %}
		</ul>
    </div>

gb/mainapp/templates/mainapp/includes/inc_menu.html
<div class="header clearfix">
	<a href="index" class="logo"></a>
		<ul class="menu">
			<li><a href="{% url 'index' %}" {% if request.resolver_match.url_name == 'index' %}
			class='active'{% endif %}>домой</a></li>
			<li><a href="{% url 'products:products' %}" {% if request.resolver_match.url_name == 'products' or request.resolver_match.url_name == 'category' %}
			class='active'{% endif %}>продукты</a></li>
			<li><a href="{% url 'contact' %}" {% if request.resolver_match.url_name == 'contact' %}
			class='active'{% endif %}>контакты</a></li>
		</ul>
	<a href="#" class="search"></a>
</div>

gb/mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block title %}
	<title>Магазин</title>
{% endblock title %}


{% block content %}
	<div class="container">
		<div class="slider">
			{% include 'mainapp/includes/inc_menu.html' %}
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% include 'mainapp/includes/inc_block_product.html'%}
			</div>
		</div>
		
		<div class="clr"></div>

	</div>
{% endblock content %}

gb/mainapp/templates/mainapp/products.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block content %}
<body>
	<div class="container">
		<div class="hero-white">
			{% include "mainapp/includes/inc_menu.html" %}
		</div>

		{% include "mainapp/includes/inc_category_menu.html" %}

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static 'img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-1.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>	
{% endblock content %}
	